spring:
  data:
    rest:
  basePath: /api
  datasource:
    url: jdbc:h2:./db/test	
    initialize: false
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update